apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-app-secrets
  namespace: hrms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: hrms/db-credentials
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: hrms/jwt-secret
        property: token
