apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hrms-netpol
  namespace: hrms
spec:
  podSelector:
    matchLabels:
      app: hrms-api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: hrms-frontend
