apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-api
  namespace: hrms-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hrms-api
  template:
    metadata:
      labels:
        app: hrms-api
    spec:
      containers:
      - name: hrms-api
        image: munnangihari/devops-week1-app:v2
        ports:
        - containerPort: 8080

