apiVersion: v1
kind: Secret
metadata:
  name: hrms-app-secrets
  namespace: rbac-demo
type: Opaque
stringData:
  DB_USERNAME: "<set-via-CI-or-kubectl>"
  DB_PASSWORD: "<set-via-CI-or-kubectl>"
  REDIS_PASSWORD: "<set-via-CI-or-kubectl>"
  JWT_SECRET: "<set-via-CI-or-kubectl>"
