apiVersion: v1
kind: ConfigMap
metadata:
  name: blackroth-config
  namespace: blackroth-capstone
data:
  DB_HOST: "dev-postgres.cyz08wy2yaof.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  REDIS_HOST: "dev-redis.gulnml.0001.use1.cache.amazonaws.com"
  REDIS_PORT: "6379"
  APP_PORT: "8000"
