pipeline {
    agent any

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Unit Tests') {
            steps {
                dir('blackroth-hrms-devsecops/backend') {
                    sh '''
                        npm ci
                        npx jest --coverage --coverageReporters=lcov
                    '''
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('blackroth-hrms-devsecops') {
                    withSonarQubeEnv('sonarqube') {
                        sh "${SCANNER_HOME}/bin/sonar-scanner"
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('blackroth-hrms-devsecops/backend') {
                    sh 'docker build -t blackroth/hrms-api:$BUILD_NUMBER .'
                }
            }
        }

stage('Trivy Scan') {
    steps {
        sh '''
        trivy image \
          --scanners vuln \
          --severity HIGH,CRITICAL \
          --exit-code 1 \
          --format json \
          -o blackroth-hrms-devsecops/security/trivy-report.json \
          blackroth/hrms-api:$BUILD_NUMBER
        '''
    }
}

        stage('Generate SBOM') {
            steps {
                sh '''
                trivy image \
                  --scanners vuln \
                  --format cyclonedx \
                  -o blackroth-hrms-devsecops/security/sbom.json \
                  blackroth/hrms-api:$BUILD_NUMBER
                '''
            }
        }

        stage('Continue') {
            steps {
                echo 'Quality Gate and Trivy checks passed, continuing pipeline'
            }
        }
    }
}

