sonar.projectKey=hrms-backend
sonar.projectName=HRMS Backend
sonar.sources=backend
sonar.tests=backend/tests
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**,backend/tests/**,backend/jest.config.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
