apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hrms
  template:
    metadata:
      labels:
        app: hrms
    spec:
      containers:
      - name: hrms
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
