{{- if .Values.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-np
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  ingress:
  {{- range .Values.networkPolicy.ingress }}
    - from:
        - podSelector:
            matchLabels:
              app: {{ . }}
  {{- end }}
{{- end }}

